### ISSUE TITLE
Want To Reproduce The Dataset

### ISSUE THREAD

**Issue by spdc-elm** [mwalmsley/galaxy_mnist#2]
Hello,
    I need a dataset with higher resolution, and I've found that the original size of the images was 3x424x424. I've read your "reproduce" folder, and tried to modify the lines about resizing the image. However, I failed because I didn't have your parquet files which were processed. 
    In the file "create_dataset.py", I found that I lacked `"gz_decals_volunteers_1_and_2_internal.parquet"` and `"latest_labels.parquet"`（see the pictures below）, which I couldn't find in the website that the downloading link in your "README.md" refers to. Could you pleaze provide me with these two parquet files so that I don't need to process all those raw datasets again? Thanks a lot!
![2022-07-17 16-04-00 的屏幕截图](https://user-images.githubusercontent.com/58126622/179389593-4bcab0f0-a40c-4a53-8652-619002547348.png)
yours,
spdc-elm

**Comment by mwalmsley** [comment]
Hi spdc-elm,

For a dataset with higher resolution, can I suggest you take a look at
github.com/mwalmsley/pytorch-galaxy-datasets

That repo has several datasets with the original (424x) images. The decals
dataset is a superset of GalaxyMNIST (which is basically a simplified
version of the decals dataset).

Let me know if that data works for you. What exactly are you trying to do?

(The reproduce folder is really for me and my records, but I'm happy to
share those files if you really need them - I just suspect the repo above
would be better for serious high rez work)

Cheers,
Mike

**Comment by spdc-elm** [comment]
I still want to use the GalaxyMNIST because I think it is lighter and more convenient. We're just building a small network and trying to use saliency mapping to explain it. I considered higher resolution would work better when generating the heatmaps. So would you please share those two files? Really thanks!

**Comment by spdc-elm** [comment]
Are you still there? Sorry for bothering. I really want to use those two files to generate higher resolution images. I'll be really grateful if you could share them!

**Comment by mwalmsley** [comment]
Sorry, yes, busy week. I think you will find all the original images in the
Zenodo repo linked in the GZ Decals paper. Download each folder, extract,
and they should have the same names as the GalaxyMNIST images allowing you
to replace them.

Note that all the images are a lot of data. I can send you only the subset
you need but not for about 3 weeks due to other commitments.

Mike

**Comment by spdc-elm** [comment]
Dr. Mike,
     Hello!
     I'm still here waiting for your files. I would appreciate it if you could take some time out of your busy schedule to send me that!

Yours,
spdc-elm

**Comment by mwalmsley** [comment]
Hi spdc-elm,

Thanks for your patience. I've now made a version with 224 pixel images of the same galaxies. I've updated the readme and load_in_pytorch.py example, but in short, just replace GalaxyMNIST with GalaxyMNISTHighrez. 

Please let me know a) if this works b) if it is definitely the same galaxies downloaded.

Yours,
Mike

**Comment by spdc-elm** [comment]
Hi Mike,

I'm glad to tell you that it works quite well!  I've checked some of the galaxies and made sure that they are the same. Thank so much for your work. Sorry for bothering you these days!

Yours,
spdc-elm

**Comment by mwalmsley** [comment]
My pleasure - I hope your work goes well. Keep me posted. I might make a
page here with ongoing projects at some point.
